run:
  concurrency: 8
  timeout: 1m
  issues-exit-code: 10
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
output:
  format: tab
  sort-results: true
linters:
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # generics
    - rowserrcheck
    - wastedassign
    - sqlclosecheck
    #
    - durationcheck
    - exhaustruct
    - gci
    - ireturn
    - revive
    - wrapcheck
    - wsl
    #
    - nonamedreturns
    - goerr113
    - gochecknoglobals
    - gomnd
    - gofumpt #timeout, used local
    - dupl
    # RELEASE TURN ON
    - unused
    - testpackage
    - forbidigo
linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - db
    ignore-decls:
      - c *gin.Context
      - s *Server
      - t testing.T
      - e error
      - T any
      - m map[string]int
  stylecheck:
    checks: [ "-ST1003" ]
  gomnd:
    ignored-numbers:
      - '32'
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
  govet:
    disable:
      - composites
  gosimple:
    checks: [ "all", "-S1028", "-S1039" ]