run:
  concurrency: 8
  timeout: 1m
  issues-exit-code: 10
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
output:
  format: tab
  sort-results: true
linters:
  enable-all: true
  disable:
  # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
  # generics
    - rowserrcheck
    - wastedassign
    - sqlclosecheck
  #
    - durationcheck
    - exhaustruct
    - gci
    - ireturn
    - revive
    - wrapcheck
    - wsl
linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - db
    ignore-decls:
      - s *Server
      - t testing.T
      - e error
      - T any
      - m map[string]int
  stylecheck:
    checks: ["-ST1003"]