server:
  port: "8000"
  host: "localhost"

postgres:
  port: "5432"
  host: "localhost"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

mongodb:
  port:
  host: "localhost"
  username:
  dbname: "mongodb"
  sslmode: "disable"