server:
  port: "8000"
  host: "localhost"
  maxHeaderBytes: "20"
  readTimeout: "10"
  writeTimeout: "10"

postgres:
  port: "5432"
  host: "localhost"
  username: "postgres"
  dbname: "postgres"
  sslMode: "disable"

mongodb:
  port: ""
  host: "localhost"
  username: ""
  dbname: "mongodb"
  sslMode: "disable"