server:
  port: "8000"
  host: "localhost"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  port: "5432"
  host: "localhost"
  username: "user"
  dbname: "user"
  sslMode: "disable"

mongodb:
  port: "27017"
  host: "localhost"
  username: "root"

redis:
  port: "6379"
  host: "localhost"
  username: ""

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 24h
  refreshTokenLength: 40
