server:
  port: "8000"
  host: "localhost"
  maxHeaderBytes: "20"
  readTimeout: "10"
  writeTimeout: "10"

postgres:
  port: "5433"
  host: "localhost"
  username: "root"
  dbname: "inno_taxi"
  sslMode: "disable"

mongodb:
  port: "5000"
  host: "localhost"
  username: "root"
  dbname: "logs"
  sslMode: "disable"

redis:
  port: "5001"
  host: "localhost"