server:
  port: 8000
  host: "localhost"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

postgres:
  port: 5000
  host: "localhost"
  username: "root"
  dbname: "inno_taxi"
  sslMode: "disable"

mongodb:
  port: 27017
  host: "localhost"
  username: "root"

redis:
  port: 6379
  host: "localhost"
  username: ""

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 24h
  refreshTokenLength: 40
