name: Go

on:
  push:
    branches: [ "main", "develop", "features/*"]
  pull_request:
    branches: [ "main", "develop"]

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check via linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Build
        run: go build -v

      - name: Test
        run: go test